package com.ahmed.teacher;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.print.*;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import android.text.*;
import java.util.*;
import java.io.File;

public class MainActivity extends Activity {
    private LinearLayout root;
    private int grade=4, cls=1;
    private String week="الأسبوع الأول";
    private ArrayList<String> names=new ArrayList<>();
    private final Handler handler=new Handler(Looper.getMainLooper());
    private final String[] weeks={"الأسبوع الأول","الأسبوع الثاني","الأسبوع الثالث","الأسبوع الرابع","الأسبوع الخامس","الأسبوع السادس","الأسبوع السابع","الأسبوع الثامن","الأسبوع التاسع","الأسبوع العاشر","الأسبوع الحادي عشر","الأسبوع الثاني عشر","الأسبوع الثالث عشر","الأسبوع الرابع عشر","الأسبوع الخامس عشر","الأسبوع السادس عشر","الأسبوع السابع عشر","الأسبوع الثامن عشر"};
    private final String[] weekDates={"12/09/2026","19/09/2026","26/09/2026","03/10/2026","10/10/2026","17/10/2026","24/10/2026","31/10/2026","07/11/2026","14/11/2026","21/11/2026","28/11/2026","05/12/2026","12/12/2026","19/12/2026","26/12/2026","02/01/2027","09/01/2027"};
    private int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
    private TextView tv(String s,float z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.rgb(25,45,90));t.setGravity(Gravity.CENTER);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setPadding(dp(8),dp(8),dp(8),dp(8));return t;}
    private Button btn(String s,View.OnClickListener l){Button x=new Button(this);x.setText(s);x.setTextSize(15);x.setAllCaps(false);x.setOnClickListener(l);x.setTextColor(Color.rgb(25,45,90));x.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(52)));return x;}
    private GradientDrawable cardBg(){GradientDrawable g=new GradientDrawable();g.setColor(Color.WHITE);g.setStroke(dp(1),Color.rgb(215,220,230));g.setCornerRadius(dp(12));return g;}
    private void base(String h){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(12),dp(12),dp(12),dp(20));root.setBackgroundColor(Color.rgb(246,248,252));sc.addView(root);setContentView(sc);root.addView(tv(h,24));}
    private void section(String s){TextView t=tv(s,15);t.setGravity(Gravity.RIGHT);t.setTextColor(Color.rgb(70,90,125));t.setPadding(dp(8),dp(14),dp(8),dp(5));root.addView(t);}
    private SharedPreferences prefs(){return getPreferences(0);}
    @Override public void onCreate(Bundle b){super.onCreate(b);home();}
    private void home(){base("📚 سجل المعلم");TextView sub=tv("التقييمات الأسبوعية والحضور والدرجات",16);sub.setTextColor(Color.rgb(70,90,125));root.addView(sub);TextView owner=tv("© Ahmed Mostafa Abonajy  •  إصدار 2026",11);owner.setTextColor(Color.GRAY);root.addView(owner);section("إعدادات المدرسة");root.addView(btn("🏫 بيانات المدرسة / اسم المعلم / المادة",v->schoolData()));section("الفصول الدراسية");root.addView(btn("الصف الرابع  •  3 فصول",v->classes(4)));root.addView(btn("الصف الخامس  •  3 فصول",v->classes(5)));root.addView(btn("الصف السادس  •  3 فصول",v->classes(6)));section("التقارير والملفات");root.addView(btn("📊 التقييم الشهري والاختبارات",v->monthly()));root.addView(btn("📤 تصدير إلى Excel",v->exportExcel()));root.addView(btn("🖨 طباعة",v->printReport()));}
    private EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextSize(16);e.setSingleLine(true);e.setPadding(dp(10),dp(10),dp(10),dp(10));return e;}
    private void schoolData(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText school=field("اسم المدرسة",prefs().getString("school",""));EditText teacher=field("اسم المعلم",prefs().getString("teacher","Ahmed Mostafa Abonajy"));EditText subject=field("المادة",prefs().getString("subject",""));box.addView(school);box.addView(teacher);box.addView(subject);new AlertDialog.Builder(this).setTitle("🏫 بيانات المدرسة").setView(box).setPositiveButton("حفظ",(d,w)->{prefs().edit().putString("school",school.getText().toString()).putString("teacher",teacher.getText().toString()).putString("subject",subject.getText().toString()).apply();Toast.makeText(this,"تم حفظ البيانات",Toast.LENGTH_SHORT).show();}).setNegativeButton("إلغاء",null).show();}
    private void classes(int g){grade=g;names.clear();base("الصف "+g);section("اختر الفصل");for(int i=1;i<=3;i++){final int c=i;root.addView(btn("الفصل "+c+"  •  "+studentCount(c)+" طالب",v->open(c)));}root.addView(btn("⬅ رجوع",v->home()));}
    private int studentCount(int c){String s=prefs().getString("names_"+grade+"_"+c,"");return s.isEmpty()?0:s.split("\\n").length;}
    private void load(){String s=prefs().getString("names_"+grade+"_"+cls,"");if(!s.isEmpty())names.addAll(Arrays.asList(s.split("\\n")));}
    private void saveNames(){StringBuilder s=new StringBuilder();for(String n:names)if(n!=null&&!n.trim().isEmpty()){if(s.length()>0)s.append('\n');s.append(n.trim());}prefs().edit().putString("names_"+grade+"_"+cls,s.toString()).apply();}
    private void open(int c){cls=c;names.clear();load();base("الصف "+grade+" - الفصل "+c);root.addView(btn("📥 إضافة / استبدال الأسماء من Excel",v->pickExcel()));root.addView(tv("عدد الطلاب: "+names.size()+"  •  الحد المقترح 50+ طالب",16));root.addView(btn("➕ إضافة طالب جديد",v->addStudentDialog()));root.addView(btn("🗑 حذف طالب",v->deleteStudentDialog()));root.addView(btn("🗑 حذف جميع الطلاب",v->deleteAllStudentsDialog()));Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,weeks));root.addView(sp);root.addView(btn("▶ بدء التقييم الأسبوعي",v->{week=sp.getSelectedItem().toString();assessment();}));root.addView(btn("📅 التقييم الشهري والاختبارات",v->monthly()));root.addView(btn("📤 تصدير الفصل إلى Excel",v->exportExcel()));root.addView(btn("🖨 طباعة الفصل",v->printReport()));root.addView(btn("⬅ رجوع",v->classes(grade)));}
    private void addStudentDialog(){final EditText input=field("اسم الطالب","");new AlertDialog.Builder(this).setTitle("➕ إضافة طالب جديد").setMessage("اكتب اسم الطالب بالكامل").setView(input).setNegativeButton("إلغاء",null).setPositiveButton("إضافة",(d,w)->{String n=input.getText().toString().trim();if(n.isEmpty()){Toast.makeText(this,"اكتب الاسم أولًا",Toast.LENGTH_SHORT).show();return;}for(String old:names)if(old.equalsIgnoreCase(n)){Toast.makeText(this,"الطالب موجود بالفعل",Toast.LENGTH_SHORT).show();return;}names.add(n);saveNames();open(cls);}).show();}
    private void deleteStudentDialog(){if(names.isEmpty()){Toast.makeText(this,"لا يوجد طلاب",Toast.LENGTH_SHORT).show();return;}String[] a=names.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("🗑 اختر الطالب").setItems(a,(d,w)->confirmDeleteStudent(a[w])).setNegativeButton("إلغاء",null).show();}
    private void confirmDeleteStudent(String n){new AlertDialog.Builder(this).setTitle("تأكيد الحذف").setMessage("سيتم حذف الطالب ودرجاته وحضوره:\n\n"+n).setNegativeButton("إلغاء",null).setPositiveButton("حذف",(d,w)->{deleteStudentData(n);names.remove(n);saveNames();open(cls);}).show();}
    private void deleteStudentData(String n){String marker=grade+"_"+cls+"_"+n.hashCode()+"_";SharedPreferences.Editor e=prefs().edit();for(String k:prefs().getAll().keySet())if(k.contains(marker)||k.equals("exam1_"+grade+"_"+cls+"_"+n.hashCode())||k.equals("exam2_"+grade+"_"+cls+"_"+n.hashCode()))e.remove(k);e.apply();}
    private void deleteAllStudentsDialog(){if(names.isEmpty()){Toast.makeText(this,"لا يوجد طلاب",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("⚠️ حذف جميع الطلاب").setMessage("سيتم حذف الطلاب ودرجاتهم وحضورهم. لا يمكن التراجع.").setNegativeButton("إلغاء",null).setPositiveButton("حذف الكل",(d,w)->{clearClassData();names.clear();saveNames();open(cls);}).show();}
    private void clearClassData(){String marker=grade+"_"+cls+"_";SharedPreferences.Editor e=prefs().edit();for(String k:prefs().getAll().keySet())if(k.equals("names_"+grade+"_"+cls)||k.contains(marker))e.remove(k);e.apply();}
    private void pickExcel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,101);}
    @Override public void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==101&&c==RESULT_OK&&d!=null)try{names=ExcelReader.readNames(this,d.getData());saveNames();Toast.makeText(this,"تم استيراد "+names.size()+" اسمًا",Toast.LENGTH_SHORT).show();open(cls);}catch(Exception e){Toast.makeText(this,"تعذر قراءة الملف: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    private String scoreKey(String student,String w,String part){return "score_"+grade+"_"+cls+"_"+student.hashCode()+"_"+w+"_"+part;}
    private int savedScore(String s,String w,String p){return prefs().getInt(scoreKey(s,w,p),0);}
    private void saveScore(String s,String w,String p,int v){prefs().edit().putInt(scoreKey(s,w,p),Math.max(0,Math.min(maxFor(p),v))).apply();}
    private int maxFor(String p){return "weekly".equals(p)?10:5;}
    private String absentKey(String s,String w){return "absent_"+grade+"_"+cls+"_"+s.hashCode()+"_"+w;}
    private boolean isAbsent(String s,String w){return prefs().getBoolean(absentKey(s,w),false);}
    private void saveAbsent(String s,String w,boolean v){prefs().edit().putBoolean(absentKey(s,w),v).apply();}
    private String lockKey(){return "locked_"+grade+"_"+cls+"_"+week;}
    private boolean isWeekLocked(){return prefs().getBoolean(lockKey(),false);}
    private void setWeekLocked(boolean v){prefs().edit().putBoolean(lockKey(),v).apply();}
    private int weekIndex(){for(int i=0;i<weeks.length;i++)if(weeks[i].equals(week))return i;return 0;}
    private String dateKey(){return "date_"+grade+"_"+cls+"_"+weekIndex();}
    private String weekDate(){return prefs().getString(dateKey(),weekDates[weekIndex()]);}
    private String dayName(String date){try{java.text.SimpleDateFormat f=new java.text.SimpleDateFormat("dd/MM/yyyy",Locale.US);Date d=f.parse(date);String[] days={"الأحد","الإثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"};Calendar c=Calendar.getInstance();c.setTime(d);return days[c.get(Calendar.DAY_OF_WEEK)-1];}catch(Exception e){return "";}}
    private void chooseDate(){try{String[] p=weekDate().split("/");DatePickerDialog dlg=new DatePickerDialog(this,(v,y,m,d)->{String s=String.format(Locale.US,"%02d/%02d/%04d",d,m+1,y);prefs().edit().putString(dateKey(),s).apply();assessment();},Integer.parseInt(p[2]),Integer.parseInt(p[1])-1,Integer.parseInt(p[0]));dlg.show();}catch(Exception e){Toast.makeText(this,"تعذر اختيار التاريخ",Toast.LENGTH_SHORT).show();}}
    private void goPreviousWeek(){int i=weekIndex();if(i>0){week=weeks[i-1];assessment();}else Toast.makeText(this,"أنت في الأسبوع الأول",Toast.LENGTH_SHORT).show();}
    private void goNextWeek(){int i=weekIndex();if(i<weeks.length-1){week=weeks[i+1];assessment();}else Toast.makeText(this,"هذا آخر أسبوع",Toast.LENGTH_SHORT).show();}
    private boolean hasWeekData(String n,String w){return savedScore(n,w,"beh")>0||savedScore(n,w,"hw")>0||savedScore(n,w,"copy")>0||savedScore(n,w,"weekly")>0||isAbsent(n,w);}
    private boolean isComplete(String n){return hasWeekData(n,week)&&!isAbsent(n,week)&&savedScore(n,week,"hw")>=5&&savedScore(n,week,"copy")>=5&&savedScore(n,week,"weekly")>=10&&savedScore(n,week,"beh")>=5;}
    private int missingCount(){int c=0;for(String n:names)if(!isComplete(n))c++;return c;}
    private void assessment(){
        base("الصف "+grade+" - الفصل "+cls);
        root.addView(tv("📝 التقييم الأسبوعي",21));
        TextView date=tv(week+"\n📅 "+dayName(weekDate())+"  "+weekDate(),16);date.setBackground(cardBg());root.addView(date);
        root.addView(btn("📅 تغيير تاريخ هذا التقييم",v->chooseDate()));
        Spinner ws=new Spinner(this);ws.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,weeks));ws.setSelection(weekIndex());ws.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){if(!weeks[pos].equals(week)){week=weeks[pos];assessment();}}});root.addView(ws);
        LinearLayout nav=new LinearLayout(this);nav.setWeightSum(2);Button prev=btn("⬅ السابق",v->goPreviousWeek());Button next=btn("التالي ➡",v->goNextWeek());prev.setLayoutParams(new LinearLayout.LayoutParams(0,dp(50),1));next.setLayoutParams(new LinearLayout.LayoutParams(0,dp(50),1));nav.addView(prev);nav.addView(next);root.addView(nav);
        final boolean locked=isWeekLocked();
        TextView state=tv(locked?"🔒 التقييم مقفول":"✏️ التقييم مفتوح • الحفظ تلقائي",14);state.setTextColor(locked?Color.rgb(190,70,70):Color.rgb(35,130,80));root.addView(state);
        root.addView(btn(locked?"🔓 فتح التقييم للتعديل":"🔒 قفل التقييم الأسبوعي",v->{if(locked)confirmUnlock();else confirmLock();}));
        TextView progress=tv("📊 المكتمل: "+(names.size()-missingCount())+" / "+names.size()+"   •   المتبقي: "+missingCount(),14);progress.setBackground(cardBg());root.addView(progress);
        if(!locked){
            LinearLayout tools=new LinearLayout(this);tools.setOrientation(LinearLayout.VERTICAL);
            tools.addView(btn("⚡ التقييم السريع",v->quickMode()));
            tools.addView(btn("🔎 بحث / فلترة الطلاب",v->showStudentTools()));
            tools.addView(btn("▶️ استكمال الناقص",v->focusFirstMissing()));
            tools.addView(btn("📋 نسخ تقييم الأسبوع السابق",v->copyPreviousWeek()));
            tools.addView(btn("👥 درجة جماعية",v->bulkScoreDialog()));
            root.addView(tools);
        }else root.addView(btn("🔎 بحث / فلترة الطلاب",v->showStudentTools()));
        root.addView(tv("درجات التقييم • اكتب الدرجة وسيتم الحفظ والانتقال تلقائيًا",13));
        if(names.isEmpty())root.addView(tv("لا يوجد طلاب. أضف أسماء من Excel أو أضف طالبًا جديدًا.",15));
        for(String n:new ArrayList<>(names))addStudent(n,locked);
        root.addView(btn("➕ إضافة طالب",v->addStudentDialog()));
        root.addView(btn("🗑 حذف طالب",v->deleteStudentDialog()));
        root.addView(btn("🗑 حذف درجات هذا التقييم للكل",v->deleteAllScoresDialog()));
        root.addView(btn("⬅ رجوع للفصل",v->open(cls)));
    }
    private void showStudentTools(){
        LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);
        EditText search=field("اكتب جزءًا من اسم الطالب","");
        Spinner filter=new Spinner(this);filter.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"الكل","مكتمل","ناقص","غائب"}));
        box.addView(search);box.addView(filter);
        new AlertDialog.Builder(this).setTitle("🔎 بحث وفلترة").setView(box).setNegativeButton("إلغاء",null).setPositiveButton("عرض",(d,w)->{String q=search.getText().toString().trim();String f=filter.getSelectedItem().toString();showFiltered(q,f);}).show();
    }
    private void showFiltered(String q,String f){
        base("🔎 نتائج الطلاب");
        for(String n:names){boolean match=q.isEmpty()||n.toLowerCase(Locale.ROOT).contains(q.toLowerCase(Locale.ROOT));boolean ok=f.equals("الكل")||(f.equals("مكتمل")&&isComplete(n))||(f.equals("ناقص")&&!isComplete(n)&&!isAbsent(n,week))||(f.equals("غائب")&&isAbsent(n,week));if(match&&ok)root.addView(tv("👤 "+n+"   •   "+(isAbsent(n,week)?"غائب":isComplete(n)?"مكتمل":"ناقص"),16));}
        root.addView(btn("⬅ رجوع للتقييم",v->assessment()));
    }
    private void focusFirstMissing(){for(String n:names)if(!isComplete(n)){Toast.makeText(this,"ابدأ من: "+n,Toast.LENGTH_LONG).show();return;}Toast.makeText(this,"🎉 كل الطلاب مكتملون",Toast.LENGTH_SHORT).show();}
    private void quickMode(){
        if(names.isEmpty()){Toast.makeText(this,"لا يوجد طلاب",Toast.LENGTH_SHORT).show();return;}
        ArrayList<String> pending=new ArrayList<>();for(String n:names)if(!isComplete(n))pending.add(n);
        if(pending.isEmpty()){Toast.makeText(this,"كل الطلاب مكتملون في هذا الأسبوع",Toast.LENGTH_SHORT).show();return;}
        quickStudent(pending,0);
    }
    private void quickStudent(ArrayList<String> list,int index){
        if(index>=list.size()){assessment();Toast.makeText(this,"تم إنهاء التقييم السريع",Toast.LENGTH_SHORT).show();return;}
        String n=list.get(index);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);
        TextView hint=tv("الطالب "+(index+1)+" من "+list.size()+"\n👤 "+n,18);hint.setBackground(cardBg());box.addView(hint);
        EditText hw=scoreEdit("واجب /5",5),cp=scoreEdit("كراسة /5",5),we=scoreEdit("تقييم أسبوعي /10",10),be=scoreEdit("سلوك /5",5);
        loadEdit(hw,savedScore(n,week,"hw"));loadEdit(cp,savedScore(n,week,"copy"));loadEdit(we,savedScore(n,week,"weekly"));loadEdit(be,savedScore(n,week,"beh"));box.addView(hw);box.addView(cp);box.addView(we);box.addView(be);
        new AlertDialog.Builder(this).setTitle("⚡ التقييم السريع").setView(box).setNegativeButton("إلغاء",null).setPositiveButton(index==list.size()-1?"حفظ وإنهاء":"حفظ والتالي",(d,w)->{saveScore(n,week,"hw",num(hw,5));saveScore(n,week,"copy",num(cp,5));saveScore(n,week,"weekly",num(we,10));saveScore(n,week,"beh",num(be,5));quickStudent(list,index+1);}).show();
    }
    private void copyPreviousWeek(){int i=weekIndex();if(i<=0){Toast.makeText(this,"لا يوجد أسبوع سابق",Toast.LENGTH_SHORT).show();return;}String prev=weeks[i-1];new AlertDialog.Builder(this).setTitle("📋 نسخ الأسبوع السابق").setMessage("سيتم نسخ درجات "+prev+" إلى "+week+" للطلاب الذين لديهم درجات سابقة. هل تريد المتابعة؟").setNegativeButton("إلغاء",null).setPositiveButton("نسخ",(d,w)->{for(String n:names){if(hasWeekData(n,prev)&&!hasWeekData(n,week)){saveScore(n,week,"hw",savedScore(n,prev,"hw"));saveScore(n,week,"copy",savedScore(n,prev,"copy"));saveScore(n,week,"weekly",savedScore(n,prev,"weekly"));saveScore(n,week,"beh",savedScore(n,prev,"beh"));saveAbsent(n,week,isAbsent(n,prev));}}assessment();}).show();}
    private void bulkScoreDialog(){
        if(names.isEmpty()){Toast.makeText(this,"لا يوجد طلاب",Toast.LENGTH_SHORT).show();return;}
        String[] parts={"واجب منزلي /5","كراسة الحصة /5","تقييم أسبوعي /10","المواظبة والسلوك /5"};
        new AlertDialog.Builder(this).setTitle("👥 درجة جماعية").setItems(parts,(d,which)->{final EditText input=field("الدرجة","");input.setInputType(2);int max=which==2?10:5;new AlertDialog.Builder(this).setTitle(parts[which]).setMessage("سيتم تطبيق الدرجة على كل الطلاب. يمكنك استخدام 0 أيضًا.").setView(input).setNegativeButton("إلغاء",null).setPositiveButton("تطبيق",(x,y)->{int v=num(input,max);String key=which==0?"hw":which==1?"copy":which==2?"weekly":"beh";for(String n:names)if(!isAbsent(n,week))saveScore(n,week,key,v);assessment();}).show();}).setNegativeButton("إلغاء",null).show();
    }
    private void deleteAllScoresDialog(){if(names.isEmpty()){Toast.makeText(this,"لا يوجد طلاب",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("🗑 حذف درجات التقييم").setMessage("سيتم حذف درجات جميع الطلاب في "+week+" فقط، مع الاحتفاظ بأسماء الطلاب.").setNegativeButton("إلغاء",null).setPositiveButton("حذف الدرجات",(d,w)->{SharedPreferences.Editor e=prefs().edit();for(String n:names){e.remove(scoreKey(n,week,"hw"));e.remove(scoreKey(n,week,"copy"));e.remove(scoreKey(n,week,"weekly"));e.remove(scoreKey(n,week,"beh"));e.remove(absentKey(n,week));}e.apply();Toast.makeText(this,"تم حذف درجات "+week+" للكل",Toast.LENGTH_SHORT).show();assessment();}).show();}
    private void confirmLock(){new AlertDialog.Builder(this).setTitle("🔒 قفل التقييم").setMessage("بعد القفل لن يمكن تعديل درجات هذا الأسبوع. هل تريد القفل؟").setNegativeButton("إلغاء",null).setPositiveButton("قفل",(d,w)->{setWeekLocked(true);Toast.makeText(this,"تم قفل "+week,Toast.LENGTH_SHORT).show();if(weekIndex()<weeks.length-1){week=weeks[weekIndex()+1];assessment();}else assessment();}).show();}
    private void confirmUnlock(){new AlertDialog.Builder(this).setTitle("🔓 فتح التقييم").setMessage("السماح بالتعديل على درجات هذا الأسبوع؟").setNegativeButton("إلغاء",null).setPositiveButton("فتح",(d,w)->{setWeekLocked(false);assessment();}).show();}
    private EditText scoreEdit(String hint,int max){EditText e=new EditText(this);e.setHint(hint);e.setGravity(Gravity.CENTER);e.setInputType(2);e.setTextSize(15);e.setSingleLine(true);e.setImeOptions(EditorInfo.IME_ACTION_NEXT);e.setSelectAllOnFocus(true);e.setFilters(new InputFilter[]{new InputFilter.LengthFilter((max==10||max==15)?2:1)});e.setPadding(dp(2),dp(2),dp(2),dp(2));e.setBackground(cardBg());e.setLayoutParams(new LinearLayout.LayoutParams(0,dp(58),1));return e;}
    private int num(EditText e,int max){try{return Math.max(0,Math.min(max,Integer.parseInt(e.getText().toString())));}catch(Exception x){return 0;}}
    private void loadEdit(EditText e,int v){if(v>0)e.setText(String.valueOf(v));}
    private void addStudent(String n,boolean locked){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(7),dp(8),dp(7),dp(8));card.setBackground(cardBg());TextView name=tv("👤 "+n,16);name.setGravity(Gravity.RIGHT);card.addView(name);CheckBox absent=new CheckBox(this);absent.setText("غائب ✓  (اتركه بدون علامة للحضور)");absent.setChecked(isAbsent(n,week));absent.setEnabled(!locked);card.addView(absent);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);row.setWeightSum(5);EditText hw=scoreEdit("واجب منزلي /5",5),copy=scoreEdit("كراسة الحصة /5",5),weekly=scoreEdit("تقييم أسبوعي /10",10),beh=scoreEdit("المواظبة والسلوك /5",5);loadEdit(hw,savedScore(n,week,"hw"));loadEdit(copy,savedScore(n,week,"copy"));loadEdit(weekly,savedScore(n,week,"weekly"));loadEdit(beh,savedScore(n,week,"beh"));hw.setEnabled(!locked);copy.setEnabled(!locked);weekly.setEnabled(!locked);beh.setEnabled(!locked);TextView total=tv("المجموع\n0 /25",12);total.setBackgroundColor(Color.rgb(238,243,250));total.setLayoutParams(new LinearLayout.LayoutParams(0,dp(58),1));row.addView(hw);row.addView(copy);row.addView(weekly);row.addView(beh);row.addView(total);card.addView(row);if(!locked){EditText[] fields={hw,copy,weekly,beh};String[] parts={"hw","copy","weekly","beh"};TextWatcher watcher=new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){int sum=0;for(int i=0;i<fields.length;i++){int v=num(fields[i],maxFor(parts[i]));saveScore(n,week,parts[i],v);sum+=v;}total.setText("المجموع\n"+sum+" /25");}public void afterTextChanged(Editable e){}};for(EditText e:fields)e.addTextChangedListener(watcher);for(int i=0;i<fields.length;i++)setAutoNext(fields[i],i<fields.length-1?fields[i+1]:null,i<fields.length-1?maxFor(parts[i]):maxFor(parts[i]));absent.setOnCheckedChangeListener((button,checked)->saveAbsent(n,week,checked));}int initial=savedScore(n,week,"hw")+savedScore(n,week,"copy")+savedScore(n,week,"weekly")+savedScore(n,week,"beh");total.setText("المجموع\n"+initial+" /25");root.addView(card);Space gap=new Space(this);gap.setLayoutParams(new LinearLayout.LayoutParams(1,dp(10)));root.addView(gap);}
    private void setAutoNext(EditText current,EditText next,int max){current.setOnEditorActionListener((v,action,event)->{if(action==EditorInfo.IME_ACTION_NEXT){if(next!=null){next.requestFocus();next.selectAll();}else current.clearFocus();return true;}return false;});current.addTextChangedListener(new TextWatcher(){boolean scheduled=false;public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){if(scheduled||next==null||s.length()==0)return;int value=num(current,max);boolean complete=max<=9?value>=max:(s.length()>=2&&value>=10);if(!complete)return;scheduled=true;handler.postDelayed(()->{scheduled=false;if(current.hasFocus()&&next!=null){next.requestFocus();next.selectAll();}},350);}public void afterTextChanged(Editable e){}});}
    private String fmt(double x){return x==Math.rint(x)?String.valueOf((int)x):String.format(Locale.US,"%.1f",x);}
    private void monthly(){base("📊 التقييم الشهري والاختبارات");root.addView(tv("الصف "+grade+" - الفصل "+cls,18));root.addView(tv("الاختبار الأول /15 • الاختبار الثاني /15 • المتوسط /15 • التقييمات /25 • الإجمالي /40",13));if(names.isEmpty())load();for(String n:names)addMonthlyStudent(n);root.addView(btn("🗑 حذف درجات الاختبارات للكل",v->deleteAllExamScoresDialog()));root.addView(btn("⬅ رجوع",v->open(cls)));}
    private String examKey(String n,int which){return "exam"+which+"_"+grade+"_"+cls+"_"+n.hashCode();}
    private int examScore(String n,int which){return prefs().getInt(examKey(n,which),0);}
    private void saveExam(String n,int which,int v){prefs().edit().putInt(examKey(n,which),Math.max(0,Math.min(15,v))).apply();}
    private double assessmentTotal(String n){double sum=0;int count=0;for(String w:weeks)if(hasWeekData(n,w)){sum+=savedScore(n,w,"hw")+savedScore(n,w,"copy")+savedScore(n,w,"weekly")+savedScore(n,w,"beh");count++;}return count==0?0:sum/count;}
    private void deleteAllExamScoresDialog(){if(names.isEmpty()){Toast.makeText(this,"لا يوجد طلاب",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("🗑 حذف درجات الاختبارات").setMessage("سيتم حذف الاختبار الأول والثاني لجميع الطلاب مع الاحتفاظ بأسماء الطلاب.").setNegativeButton("إلغاء",null).setPositiveButton("حذف الدرجات",(d,w)->{SharedPreferences.Editor e=prefs().edit();for(String n:names){e.remove(examKey(n,1));e.remove(examKey(n,2));}e.apply();monthly();}).show();}
    private void addMonthlyStudent(String n){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(8),dp(8),dp(8),dp(8));card.setBackground(cardBg());TextView title=tv("👤 "+n,16);title.setGravity(Gravity.RIGHT);card.addView(title);HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);EditText a=scoreEdit("الأول /15",15),b=scoreEdit("الثاني /15",15);a.setLayoutParams(new LinearLayout.LayoutParams(dp(120),dp(62)));b.setLayoutParams(new LinearLayout.LayoutParams(dp(120),dp(62)));loadEdit(a,examScore(n,1));loadEdit(b,examScore(n,2));TextView avg=tv("المتوسط\n0 /15",13),wk=tv("التقييمات\n0 /25",13),tot=tv("الإجمالي\n0 /40",13);avg.setLayoutParams(new LinearLayout.LayoutParams(dp(120),dp(62)));wk.setLayoutParams(new LinearLayout.LayoutParams(dp(130),dp(62)));tot.setLayoutParams(new LinearLayout.LayoutParams(dp(130),dp(62)));row.addView(a);row.addView(b);row.addView(avg);row.addView(wk);row.addView(tot);hs.addView(row);card.addView(hs);TextWatcher tw=new TextWatcher(){public void beforeTextChanged(CharSequence s,int x,int y,int z){}public void onTextChanged(CharSequence s,int x,int y,int z){int x1=num(a,15),x2=num(b,15);saveExam(n,1,x1);saveExam(n,2,x2);double av=(x1+x2)/2.0,wa=assessmentTotal(n);avg.setText("المتوسط\n"+fmt(av)+" /15");wk.setText("التقييمات\n"+fmt(wa)+" /25");tot.setText("الإجمالي\n"+fmt(av+wa)+" /40");}public void afterTextChanged(Editable e){}};a.addTextChangedListener(tw);b.addTextChangedListener(tw);setAutoNext(a,b,15);double av=(examScore(n,1)+examScore(n,2))/2.0,wa=assessmentTotal(n);avg.setText("المتوسط\n"+fmt(av)+" /15");wk.setText("التقييمات\n"+fmt(wa)+" /25");tot.setText("الإجمالي\n"+fmt(av+wa)+" /40");root.addView(card);}
    private void exportExcel(){if(names.isEmpty())load();if(names.isEmpty()){Toast.makeText(this,"لا يوجد طلاب لتصديرهم",Toast.LENGTH_SHORT).show();return;}try{org.apache.poi.xssf.usermodel.XSSFWorkbook wb=new org.apache.poi.xssf.usermodel.XSSFWorkbook();org.apache.poi.ss.usermodel.Sheet sh=wb.createSheet("درجات الطلاب");String[] hd={"اسم الطالب","واجب منزلي /5","كراسة الحصة /5","تقييم أسبوعي /10","المواظبة والسلوك /5","متوسط التقييمات /25","الاختبار الأول /15","الاختبار الثاني /15","متوسط الاختبارات /15","الإجمالي /40"};org.apache.poi.ss.usermodel.Row hr=sh.createRow(0);for(int i=0;i<hd.length;i++)hr.createCell(i).setCellValue(hd[i]);int r=1;for(String n:names){int hw=0,cp=0,we=0,be=0,cnt=0;for(String w:weeks)if(hasWeekData(n,w)){hw+=savedScore(n,w,"hw");cp+=savedScore(n,w,"copy");we+=savedScore(n,w,"weekly");be+=savedScore(n,w,"beh");cnt++;}double avAssess=cnt==0?0:(hw+cp+we+be)/(double)cnt;int e1=examScore(n,1),e2=examScore(n,2);double avExam=(e1+e2)/2.0;Object[] vals={n,cnt==0?0:hw/(double)cnt,cnt==0?0:cp/(double)cnt,cnt==0?0:we/(double)cnt,cnt==0?0:be/(double)cnt,avAssess,e1,e2,avExam,avAssess+avExam};org.apache.poi.ss.usermodel.Row rr=sh.createRow(r++);for(int i=0;i<vals.length;i++){if(vals[i] instanceof Number)rr.createCell(i).setCellValue(((Number)vals[i]).doubleValue());else rr.createCell(i).setCellValue(String.valueOf(vals[i]));}}for(int i=0;i<hd.length;i++)sh.setColumnWidth(i,Math.min(8000,Math.max(3500,hd[i].length()*450)));File dir=new File(getExternalFilesDir(null),"exports");if(!dir.exists())dir.mkdirs();File out=new File(dir,"Teacher_"+grade+"_"+cls+"_"+System.currentTimeMillis()+".xlsx");java.io.FileOutputStream fos=new java.io.FileOutputStream(out);wb.write(fos);fos.close();wb.close();Intent share=new Intent(Intent.ACTION_SEND);share.setType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");share.putExtra(Intent.EXTRA_STREAM,androidx.core.content.FileProvider.getUriForFile(this,getPackageName()+".fileprovider",out));share.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(share,"مشاركة ملف Excel"));}catch(Exception e){Toast.makeText(this,"تعذر إنشاء Excel: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    private void printReport(){if(Build.VERSION.SDK_INT>=19){PrintManager pm=(PrintManager)getSystemService(PRINT_SERVICE);pm.print("Teacher - "+grade+"/"+cls,new ReportPrintAdapter(this),null);}else Toast.makeText(this,"الطباعة غير مدعومة",Toast.LENGTH_SHORT).show();}
    private static class ReportPrintAdapter extends PrintDocumentAdapter{private final Context c;ReportPrintAdapter(Context x){c=x;}public void onLayout(PrintAttributes a,PrintAttributes b,CancellationSignal cs,LayoutResultCallback cb,Bundle m){if(cs.isCanceled()){cb.onLayoutCancelled();return;}cb.onLayoutFinished(new PrintDocumentInfo.Builder("Teacher-report.pdf").setContentType(PrintDocumentInfo.CONTENT_TYPE_DOCUMENT).setPageCount(1).build(),true);}public void onWrite(PageRange[] p,ParcelFileDescriptor d,CancellationSignal cs,WriteResultCallback cb){try{java.io.FileOutputStream out=new java.io.FileOutputStream(d.getFileDescriptor());out.write(("Teacher\nAhmed Mostafa Abonajy\n").getBytes("UTF-8"));out.flush();cb.onWriteFinished(new PageRange[]{PageRange.ALL_PAGES});}catch(Exception e){cb.onWriteFailed(e.getMessage());}}}
}