plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ahmed.teacher'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ahmed.teacher'
        minSdk 26
        targetSdk 35
        versionCode 11
        versionName '1.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
    implementation 'org.apache.poi:poi-ooxml:5.2.5'
}
